// Shift Summary — SHELL
// To-be visualization of shift performance summary.
// Shift summary truth is generated by the backend reporting and projection system.

import { useState } from "react";
import { CheckCircle, AlertTriangle, Clock, Package, Zap } from "lucide-react";
import { MockWarningBanner, ScreenStatusBadge, BackendRequiredNotice } from "@/app/components";
import { useI18n } from "@/app/i18n";

const MOCK_SHIFTS = [
  { id: "S1", label: "Shift 1 (06:00–14:00)" },
  { id: "S2", label: "Shift 2 (14:00–22:00)" },
  { id: "S3", label: "Shift 3 (22:00–06:00)" },
];

const MOCK_LINES = [
  { id: "ALL", label: "All Lines" },
  { id: "LINE-A", label: "Line A" },
  { id: "LINE-B", label: "Line B" },
  { id: "LINE-C", label: "Line C" },
];

interface MockBlockerItem {
  operationCode: string;
  operationName: string;
  workOrder: string;
  reason: string;
  duration: string;
}

const MOCK_BLOCKERS: MockBlockerItem[] = [
  {
    operationCode: "OP-030",
    operationName: "Surface Grind",
    workOrder: "WO-2026-004",
    reason: "DT-WAIT — Waiting for Material",
    duration: "38 min",
  },
];

export function ShiftSummary() {
  const { t } = useI18n();
  const [selectedShift, setSelectedShift] = useState<string>(MOCK_SHIFTS[0].id);
  const [selectedLine, setSelectedLine] = useState<string>("ALL");

  return (
    <div className="flex flex-col gap-4 p-4">
      {/* Shell disclosure banner */}
      <MockWarningBanner phase="SHELL" />

      {/* Header */}
      <div className="flex items-center gap-3">
        <h1 className="text-2xl font-semibold text-gray-900">
          {t("shiftSummary.title")}
        </h1>
        <ScreenStatusBadge phase="SHELL" />
      </div>

      {/* Backend required notice */}
      <BackendRequiredNotice message={t("shiftSummary.notice.shell")} />

      {/* Filters */}
      <div className="flex items-center gap-3">
        <select
          value={selectedShift}
          onChange={(e) => setSelectedShift(e.target.value)}
          className="text-sm border border-gray-200 rounded px-3 py-1.5 text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-300"
          aria-label={t("shiftSummary.filter.shift")}
        >
          {MOCK_SHIFTS.map((s) => (
            <option key={s.id} value={s.id}>{s.label}</option>
          ))}
        </select>
        <select
          value={selectedLine}
          onChange={(e) => setSelectedLine(e.target.value)}
          className="text-sm border border-gray-200 rounded px-3 py-1.5 text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-300"
          aria-label={t("shiftSummary.filter.line")}
        >
          {MOCK_LINES.map((l) => (
            <option key={l.id} value={l.id}>{l.label}</option>
          ))}
        </select>
      </div>

      {/* Summary KPI grid */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        <div className="bg-green-50 rounded-lg border border-green-200 p-3">
          <div className="flex items-center gap-1 text-xs text-green-600 mb-1">
            <CheckCircle className="w-3 h-3" />
            {t("shiftSummary.metric.opsCompleted")}
          </div>
          <div className="text-2xl font-bold text-green-800">24</div>
        </div>
        <div className="bg-blue-50 rounded-lg border border-blue-200 p-3">
          <div className="flex items-center gap-1 text-xs text-blue-600 mb-1">
            <Clock className="w-3 h-3" />
            {t("shiftSummary.metric.opsInProgress")}
          </div>
          <div className="text-2xl font-bold text-blue-800">6</div>
        </div>
        <div className="bg-red-50 rounded-lg border border-red-200 p-3">
          <div className="flex items-center gap-1 text-xs text-red-600 mb-1">
            <AlertTriangle className="w-3 h-3" />
            {t("shiftSummary.metric.opsBlocked")}
          </div>
          <div className="text-2xl font-bold text-red-800">1</div>
        </div>
        <div className="bg-amber-50 rounded-lg border border-amber-200 p-3">
          <div className="flex items-center gap-1 text-xs text-amber-600 mb-1">
            <Clock className="w-3 h-3" />
            {t("shiftSummary.metric.totalDowntime")}
          </div>
          <div className="text-2xl font-bold text-amber-800">145 min</div>
        </div>
        <div className="bg-white rounded-lg border border-gray-200 p-3">
          <div className="flex items-center gap-1 text-xs text-gray-600 mb-1">
            <Package className="w-3 h-3" />
            {t("shiftSummary.metric.qtyProduced")}
          </div>
          <div className="text-2xl font-bold text-gray-800">312</div>
        </div>
        <div className="bg-white rounded-lg border border-gray-200 p-3">
          <div className="flex items-center gap-1 text-xs text-gray-600 mb-1">
            <Zap className="w-3 h-3" />
            {t("shiftSummary.metric.defects")}
          </div>
          <div className="text-2xl font-bold text-gray-800">4</div>
        </div>
      </div>

      {/* Blockers section */}
      <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
        <div className="flex items-center gap-2 text-sm font-semibold text-gray-700 border-b border-gray-100 px-4 py-3">
          <AlertTriangle className="w-4 h-4 text-red-500" />
          {t("shiftSummary.section.blockers")}
        </div>
        {MOCK_BLOCKERS.length === 0 ? (
          <p className="text-sm text-gray-400 italic p-4">{t("shiftSummary.empty")}</p>
        ) : (
          <div className="divide-y divide-gray-100">
            {MOCK_BLOCKERS.map((item, idx) => (
              <div key={idx} className="px-4 py-3 flex flex-col gap-1">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-gray-800">{item.operationCode} — {item.operationName}</span>
                  <span className="text-xs text-gray-500">{item.workOrder}</span>
                </div>
                <div className="text-xs text-amber-700">Reason: {item.reason} | Duration: {item.duration}</div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* AI Summary — clearly demo-only */}
      <div className="bg-white rounded-lg border border-indigo-200 p-4">
        <div className="flex items-center gap-2 text-sm font-semibold text-indigo-700 border-b border-indigo-100 pb-2 mb-3">
          <Zap className="w-4 h-4 text-indigo-400" />
          {t("shiftSummary.aiSummary.label")}
          <span className="text-xs font-normal text-indigo-400 ml-1">(Future / Demo)</span>
        </div>
        <p className="text-sm text-indigo-500 italic">{t("shiftSummary.aiSummary.demo")}</p>
      </div>

      <p className="text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded px-3 py-2">
        ⚠ All shift data shown above is static demonstration data. Real shift summaries require backend reporting and projection API integration.
      </p>
    </div>
  );
}
