/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ftyrfhfjvowcqsxsjtlq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0eXJmaGZqdm93Y3FzeHNqdGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyMjgzNjMsImV4cCI6MjA4OTgwNDM2M30.WUlo1tb-ZnPLHk9q822Doy2IkilD9m4-NSaZTStfTlM"